### PR TITLE
build: fail fast in deb Makefile and allow overriding the Python interpreter

### PR DESCRIPTION
**Pull request by wmann-celonis**
## Problem

Running `make` to build the `.deb` packages fails with a misleading **`debian/changelog` missing** error. That is a *downstream symptom*, not the root cause.

The `debian/changelog` (and the rest of the package's `debian/` tree) is generated by `stdeb`'s `sdist_dsc` step. That step is what actually fails — but the recipes use `.ONESHELL:` **without** `set -e`, so on failure the recipe keeps going: `cd deb_dist/<pkg>-*` silently no-ops (the glob never matches), and `dpkg-buildpackage` then runs in the **repo root**, whose `debian/` has only `compat` + `homccd.service` and no `changelog`. Hence the confusing error.

`sdist_dsc` fails for environment reasons such as:
- the `python3` that `make` invokes not having `stdeb` installed (`error: invalid command 'sdist_dsc'`), or
- `stdeb 0.10.0` being incompatible with **Python 3.12+** (`AttributeError: module 'configparser' has no attribute 'SafeConfigParser'`).

## Fix

Makefile hardening only — surface the real failure and make the interpreter selectable:

- `.SHELLFLAGS := -ec` so recipes abort at the first failing command instead of limping into the changelog error.
- `PYTHON ?= python3`, used for both `sdist_dsc` calls, so the build can target an interpreter with a working stdeb, e.g. `make PYTHON=python3.11 all`.

## Notes

- This does not itself make `stdeb` work on Python 3.12; producing `.deb`s still requires an interpreter ≤ 3.11 with a working stdeb (or a jammy build environment as the README assumes). The build now reports that clearly rather than masking it.
- No behavior change to a working build.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by wmann-celonis** [comment]
No longer needed due to #104
